<a href="https://colab.research.google.com/github/MrSidShah/Complete-Python-3-Bootcamp/blob/master/Colab_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/bbwieland/ncaa-projections/main/data/KenPomGamesCleaned.csv'
df = pd.read_csv(url)

# Display the first 10 rows of the DataFrame
df.head(10)

,team_rk,team,opponent_rk,opponent,result,poss,ot,pre_wp,location,w,...,w_conference_proj,l_conference_proj,date,game_id,tiers_of_joy,win_loss,team_score,opp_score,team_ppp,opp_ppp
0,7,Houston,219,Northern Colorado,"W, 83-36",64,0,NaN,Home,1,...,0,0,2022-11-07,87,NaN,1,83,36,1.296875,0.562500
1,6,Houston,210,Saint Joseph's,"W, 81-55",69,0,NaN,Neutral,2,...,0,0,2022-11-11,299,NaN,1,81,55,1.173913,0.797101
2,4,Houston,59,Oral Roberts,"W, 83-45",67,0,NaN,Home,3,...,0,0,2022-11-14,496,B,1,83,45,1.238806,0.671642
3,4,Houston,307,Texas Southern,"W, 83-48",66,0,NaN,Home,4,...,0,0,2022-11-16,615,NaN,1,83,48,1.257576,0.727273
4,3,Houston,47,Oregon,"W, 66-56",60,0,NaN,Away,5,...,0,0,2022-11-20,832,A,1,66,56,1.100000,0.933333
5,2,Houston,75,Kent St.,"W, 49-44",70,0,NaN,Home,6,...,0,0,2022-11-26,1114,NaN,1,49,44,0.700000,0.628571
6,2,Houston,179,Norfolk St.,"W, 100-52",64,0,NaN,Home,7,...,0,0,2022-11-29,1212,NaN,1,100,52,1.562500,0.812500
7,1,Houston,8,Saint Mary's,"W, 53-48",56,0,NaN,Semi-Home,8,...,0,0,2022-12-03,1464,A,1,53,48,0.946429,0.857143
8,1,Houston,226,North Florida,"W, 76-42",61,0,NaN,Home,9,...,0,0,2022-12-06,1548,NaN,1,76,42,1.245902,0.688525
9,1,Houston,3,Alabama,"L, 71-65",72,0,NaN,Home,9,...,0,0,2022-12-10,1691,A,0,65,71,0.902778,0.986111